# -*- coding: utf-8 -*-
"""SRC streamlit

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17jxOzdmjN2s4yIx6XSB5p9NMhaB32x_7
"""

!pip install -q streamlit

import streamlit as st
import pandas as pd
import numpy as np

import streamlit as st
# add page title
st.title("My Iris Dataset Dashboard")
import streamlit as st
# streamlit page config
st.set_page_config(
    page_title="SRC sentiment analysis Dashboard",  # the page title shown in the browser tab
    page_icon=":bar_chart:",  # the page favicon shown in the browser tab
    layout="wide",  # page layout : use the entire screen
)
# add page title
st.title("Sentiment analysis Dashboard :bar_chart::needle:")

import streamlit as st
from PIL import Image
...
# about dataset section
st.header("About SRC")
st.write("""The Singapore Red Cross (SRC) is a homegrown humanitarian organization established in 1949, dedicated to relieving suffering, protecting human lives, and responding to emergencies. As an independent organization within the international Red Cross movement, it serves the vulnerable through blood donor recruitment, a home for the disabled, elder aid, food aid, and transport aid.    """)
redcross_image = Image.open("/content/Singapore_Red_Cross.jpg")
st.image(redcross_image)

import streamlit as st
from PIL import Image
import seaborn as sns

df = pd.read_csv('/content/SRC_Sentiment_Final_Report.csv')
# get column and species names
attributes = df.columns[:-1].tolist()
sentiment_label = df['sentiment_label'].unique().tolist()
...

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(layout="wide")

# ---- Load data (replace with your actual load) ----
# df = pd.read_csv("your_file.csv")
# If Excel:
# df = pd.read_excel("SRC_Sentiment_Final_Report.xlsx", sheet_name="...")

# Example: assume df already exists
# Required columns: date_published, source
required = {"date_published", "source"}
missing = required - set(df.columns)
if missing:
    st.error(f"Missing columns: {missing}")
    st.stop()

# ---- Parse dates safely ----
df["date_published"] = pd.to_datetime(df["date_published"], errors="coerce")
df = df.dropna(subset=["date_published"])

# ---- Map raw sources to your 6 categories ----
def map_source(row):
    s = str(row.get("source", "")).strip().lower()
    # optionally use other columns to distinguish transcription vs comments
    text = str(row.get("comment_text", "")).strip()

    if "youtube" in s:
        # Heuristic: if comment_text exists -> YouTube comments
        # If you have a better field (e.g., content_type), use that instead.
        return "YouTube comments" if text else "YouTube transcription"

    if "reddit" in s:
        return "Reddit"
    if "facebook" in s or s == "fb":
        return "Facebook"
    if "instagram" in s or s == "ig":
        return "Instagram"

    # Everything else treated as news/articles (tune this to your raw values)
    return "News articles"

df["source_group"] = df.apply(map_source, axis=1)

# ---- Choose granularity ----
granularity = st.selectbox("Time granularity", ["Day", "Week", "Month"], index=2)

if granularity == "Day":
    df["period"] = df["date_published"].dt.to_period("D").dt.to_timestamp()
elif granularity == "Week":
    # week starting Monday
    df["period"] = df["date_published"].dt.to_period("W-MON").dt.start_time
else:
    df["period"] = df["date_published"].dt.to_period("M").dt.to_timestamp()

# ---- Aggregate volume ----
vol = (
    df.groupby(["period", "source_group"])
      .size()
      .reset_index(name="volume")
)

# Ensure consistent legend order
source_order = [
    "News articles",
    "YouTube transcription",
    "YouTube comments",
    "Facebook",
    "Reddit",
    "Instagram",
]
vol["source_group"] = pd.Categorical(vol["source_group"], categories=source_order, ordered=True)
vol = vol.sort_values(["period", "source_group"])

# ---- Plot ----
chart_type = st.radio("Chart type", ["Multi-line", "Stacked area"], horizontal=True)

if chart_type == "Multi-line":
    fig = px.line(
        vol, x="period", y="volume", color="source_group",
        markers=True, category_orders={"source_group": source_order},
    )
else:
    fig = px.area(
        vol, x="period", y="volume", color="source_group",
        groupnorm=None, category_orders={"source_group": source_order},
    )

fig.update_layout(
    title="Post / Mention Volume Over Time by Source",
    xaxis_title="Date",
    yaxis_title="Volume",
    legend_title="Source",
    height=500,
    margin=dict(l=20, r=20, t=60, b=20),
)

st.plotly_chart(fig, use_container_width=True)

with st.expander("Aggregated data"):
    st.dataframe(vol, use_container_width=True)